---
- name: Install and Configure Vault Agent
  hosts: vault_clients
  become: true
  vars_files:
    - vars/main.yml

  tasks:
    - include_tasks: tasks/install.yml
    - include_tasks: tasks/configure.yml
    - include_tasks: tasks/service.yml

  handlers:
    - include: handlers/main.yml
