---
- name: Install and Configure Vault Agent
  hosts: all
  become: true
  vars_files:
    - vars/main.yml

  tasks:
    - include_tasks: tasks/install.yml
    - include_tasks: tasks/configure.yml
    - include_tasks: tasks/service.yml
    - include_tasks: tasks/httpd.yml

  handlers:
    - name: Reload systemd
      command: systemctl daemon-reexec

    - name: Restart Vault Agent
      systemd:
        name: vault-agent
        state: restarted