---
- name: Create Vault config dir
  ansible.builtin.file:
    path: /etc/vault
    state: directory
    mode: '0755'

- name: Create Vault Agent config file
  ansible.builtin.template:
    src: vault_agent_config.hcl.j2
    dest: /etc/vault/config.hcl
    mode: '0644'
  notify: Restart Vault Agent
