---
- name: Install Vault (Debian)
  apt:
    name: vault
    state: present
  when: ansible_os_family == "Debian"

- name: Install Vault (RHEL)
  yum:
    name: vault
    state: present
  when: ansible_os_family == "RedHat"
