---
- name: Add HashiCorp Yum GPG key
  rpm_key:
    key: https://rpm.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp Yum repository
  yum_repository:
    name: hashicorp
    description: "HashiCorp Stable - {{ ansible_distribution }}"
    baseurl: "https://rpm.releases.hashicorp.com/RHEL/{{ ansible_distribution_major_version }}/$basearch/stable"
    gpgcheck: yes
    gpgkey: https://rpm.releases.hashicorp.com/gpg
    enabled: yes
    
- name: Install Vault (RHEL)
  yum:
    name: vault
    state: present
  when: ansible_os_family == "RedHat"
